// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQP4eyamH7betjjR2G_UGveyCGpMTi7T4',
    appId: '1:396947772259:web:5041a3c5c249637f3fb956',
    messagingSenderId: '396947772259',
    projectId: 'videollamadas-flutter',
    authDomain: 'videollamadas-flutter.firebaseapp.com',
    storageBucket: 'videollamadas-flutter.firebasestorage.app',
    measurementId: 'G-MWZNGNQDKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSaZWu_IoA7Edgs0YEiQ_lY2ghmYH4HFk',
    appId: '1:396947772259:android:826624d45ee4babd3fb956',
    messagingSenderId: '396947772259',
    projectId: 'videollamadas-flutter',
    storageBucket: 'videollamadas-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkia7ZmKhkw8XqKN8JtUcI5g0F7QadvME',
    appId: '1:396947772259:ios:7a5424bcfe17ec393fb956',
    messagingSenderId: '396947772259',
    projectId: 'videollamadas-flutter',
    storageBucket: 'videollamadas-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAndroidVideollamada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkia7ZmKhkw8XqKN8JtUcI5g0F7QadvME',
    appId: '1:396947772259:ios:7a5424bcfe17ec393fb956',
    messagingSenderId: '396947772259',
    projectId: 'videollamadas-flutter',
    storageBucket: 'videollamadas-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyectoAndroidVideollamada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQP4eyamH7betjjR2G_UGveyCGpMTi7T4',
    appId: '1:396947772259:web:e9e96ba97c195f623fb956',
    messagingSenderId: '396947772259',
    projectId: 'videollamadas-flutter',
    authDomain: 'videollamadas-flutter.firebaseapp.com',
    storageBucket: 'videollamadas-flutter.firebasestorage.app',
    measurementId: 'G-PETDDVPFEV',
  );
}
